config/routes.rb
Rails.application.routes.draw do
  root 'kittens#index'
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def index
		@kitten = Kitten.all
		respond_to do |format|
			format.html
			format.json{ render :json => @kitten }
		end 
	end

	def new 
		@kitten = Kitten.new
    end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success]="Kitten created"
			redirect_to root_path
		else
			flash[:error]="Error"
			redirect_to root_path
		end 
	end 

	def show
		@kitten = Kitten.find(params[:id])
		respond_to do |format|
			format.html
			format.json{ render :json => @kitten }
		end 
	end 

	def edit
		@kitten = Kitten.find(params[:id])
	end 

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success]="Kitten updated!"
		    redirect_to root_path
		end 
	end

	def destroy
		Kitten.find(params[:id]).destroy
		redirect_to root_path
	end 

	private

	# Never trust parameters from the scary internet, only allow the white list through.
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :age %>
<%= f.text_field :age %>
<%= f.label :cuteness %>
<%= f.text_field :cuteness %>
<%= f.label :softness %>
<%= f.text_field :softness %>
<%= f.submit "Submit" %>
<% end %>

app/views/kittens/edit.html.erb
<%= render 'form' %>

app/views/kittens/index.html.erb
<br><%= link_to "New kitten", new_kitten_path %><br> <br><br>

<% @kitten.each do |f| %>
<%= f.name %>
<%= link_to 'View profile', kitten_path(id:f) %>
<%= link_to 'Destroy', f, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit',edit_kitten_path(id:f) %><br>
<% end %>

app/views/kittens/new.html.erb
<%= render 'form' %>

app/views/kittens/show.html.erb
<%= @kitten.name %><br>
<%= @kitten.age %><br>
<%= @kitten.cuteness%><br>
<%= @kitten.softness %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |key, value| %>
  	  <%= value %>
  	  <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/form.html.erb
<%= form_for(@kitten) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :age %>
<%= f.text_field :age %>
<%= f.label :cuteness %>
<%= f.text_field :cuteness %>
<%= f.label :softness %>
<%= f.text_field :softness %>
<%= f.submit "Submit" %>
<% end %>